<?php

namespace AppBundle\Repository;

/**
 * FurthersubcategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FurthersubcategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
