<?php

namespace AppBundle\Repository;

/**
 * SubsubsubcategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubsubsubcategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
