<?php

namespace AppBundle\Repository;

/**
 * SwapPreferenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SwapPreferenceRepository extends \Doctrine\ORM\EntityRepository
{
}
