<?php

namespace AppBundle\Repository\Taxonomy;

/**
 * FurtherSubCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FurtherSubCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
