<?php

namespace AppBundle\Repository\Taxonomy;

/**
 * FurtherSubCategory2Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FurtherSubCategory2Repository extends \Doctrine\ORM\EntityRepository
{
}
