<?php

namespace AppBundle\Repository\Taxonomy;

/**
 * SubcategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubCategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByParentId($category)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p.id, p.name FROM AppBundle:Taxonomy\SubCategory p WHERE p.parentCategory=:category AND p.isActive=1 ORDER BY p.name ASC'
            )
            ->setParameter('category', $category)
            ->getResult();
    }
}
