<?php

namespace AppBundle\Repository\Taxonomy;

/**
 * SubsubCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubsubCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
