<?php

namespace AppBundle\Repository\Taxonomy;

/**
 * SubsubCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubsubCategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByParentId($parent)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p.id, p.name FROM AppBundle:Taxonomy\SubsubCategory p WHERE p.parentSubCategory=:sub_category AND p.isActive=1 ORDER BY p.name ASC'
            )
            ->setParameter('sub_category', $parent)
            ->getResult();
    }
}
