<?php

namespace AppBundle\Repository\Taxonomy;

/**
 * SubsubsubCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubsubsubCategoryRepository extends \Doctrine\ORM\EntityRepository
{    
    public function findByParentId($parent)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p.id, p.name FROM AppBundle:Taxonomy\SubsubsubCategory p WHERE p.parentSubSubCategory=:parent AND p.isActive=1 ORDER BY p.name ASC'
            )
            ->setParameter('parent', $parent)
            ->getResult();
    }    
}
