<?php

namespace AppBundle\Repository\Taxonomy;

/**
 * SubsubsubCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubsubsubCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
