<?php

namespace AppBundle\Repository\Taxonomy;

/**
 * SubsubcategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubsubcategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
