<?php

namespace AppBundle\Repository\Product;

/**
 * ProductTaxonomyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductTaxonomyRepository extends \Doctrine\ORM\EntityRepository
{
}
