<?php

namespace AppBundle\Repository\Product;

/**
 * ProductLocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductLocationRepository extends \Doctrine\ORM\EntityRepository
{
}
