<?php

namespace AppBundle\Repository\Product;

/**
 * ProductConditionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductConditionRepository extends \Doctrine\ORM\EntityRepository
{
}
